name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: list
      run: ls
    - name: pwd
      run: pwd
    - name: make
      run: make
    - name: hello_world
      run: ./hello_world
